using System.Text.Json.Serialization;

namespace ArchenaAI.Common.Semantic.Kernel.Connectors.LLM.Models
{
    /// <summary>
    /// Represents a generic response from any Large Language Model (LLM) connector.
    /// </summary>
    public sealed class LLMResponse
    {
        /// <summary>
        /// Gets or sets the unique identifier of the model response (if provided by the model provider).
        /// </summary>
        public string? Id { get; set; }

        /// <summary>
        /// Gets or sets the model name or version used for generating this response.
        /// </summary>
        public string? Model { get; set; }

        /// <summary>
        /// Gets or sets the natural language output returned by the model.
        /// </summary>
        public string? Content { get; set; }

        /// <summary>
        /// Gets or sets the reasoning or structured data (if any) produced by the model.
        /// Useful for JSON-style or tool-calling outputs.
        /// </summary>
        public string? StructuredOutput { get; set; }

        /// <summary>
        /// Gets or sets the total number of tokens consumed for this request (prompt + completion).
        /// </summary>
        public int? TotalTokens { get; set; }

        /// <summary>
        /// Gets or sets the number of tokens used for the prompt.
        /// </summary>
        public int? PromptTokens { get; set; }

        /// <summary>
        /// Gets or sets the number of tokens generated by the model.
        /// </summary>
        public int? CompletionTokens { get; set; }

        /// <summary>
        /// Gets or sets any additional metadata returned by the model (e.g., provider-specific attributes).
        /// </summary>
        public IDictionary<string, object?> Metadata { get;  } = new Dictionary<string, object?>();

        /// <summary>
        /// Gets or sets diagnostic information or error messages.
        /// </summary>
        public string? Error { get; set; }

        /// <summary>
        /// Indicates whether the response completed successfully.
        /// </summary>
        [JsonIgnore]
        public bool IsSuccess => string.IsNullOrEmpty(Error);

        /// <summary>
        /// Provides a human-friendly string representation of the response.
        /// </summary>
        public override string ToString() =>
            $"{Model ?? "UnknownModel"}: {Content ?? "[empty]"} (Tokens: {TotalTokens ?? 0})";
    }
}
